### ISSUE TITLE
Signe du gradient

### ISSUE THREAD

**Issue by gendai** [bashardudin/Epita-SCIA-OCVX#1]
Dans la fonction qui calcule le gradient pour la norme L1, le signe n'est pas conservé. La fonction renvoie donc toujours un gradient positif.

https://github.com/bashardudin/OCVX/blob/22cd4bd1d92f535e68f173ec769c294d927c5852/Notebooks/gradientDescent.ipynb#L330-L340

**Comment by bashardudin** [comment]
Tout à fait. Faites y attention ; je laisse l'issue ouverte le temps d'avoir de l'air pour pouvoir corriger ca. Ca ne devrait pas vous poser trop de problèmes. Ramenez-vous à la formulation laissée en cours.
